# Generated by Django 4.1.7 on 2023-03-11 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address_customer', to='users.customer'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.wards'),
        ),
        migrations.AddField(
            model_name='addressuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_user_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressuser',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.wards'),
        ),
    ]
